### ISSUE TITLE
Rechazado.

### ISSUE THREAD

**Issue by t0kyolover** [4GeeksAcademy/super-insta-exercise#1]
![Screenshot 2024-04-10 at 19 44 29](https://github.com/4GeeksAcademy/super-insta-exercise/assets/144109471/65b51447-ca51-438d-b176-adbdce786db3) ![Screenshot 2024-04-10 at 19 49 08](https://github.com/4GeeksAcademy/super-insta-exercise/assets/144109471/982cf4db-22c8-4cae-a13c-a1dbf05eb83f)

- [x] Mejora responsiveness de la página
- [x] *En el dropdown siempre tienes "Profile" elegido como pulsado

**Comment by ghost** [comment]
Hola Katya!! Creo que ya lo tengo todo solucionado. Disculpa y gracias!
